language: objective-c

script: echo "We don't have tests yet :("

before_deploy:
  - sh package.sh

deploy:
  provider: releases
  api_key:
    secure: SuJyf7ajl3oxxIrG+LgLtMBfacbHSmqU864F91Ndg7qHTj1WoBsj8GaVMqjFynVc8kOCd3dUspHvAUrqIqzraSwTeVpCdyPZ9edhhoGlUx26s0Y4zAx4LNgIupz+zZL8QilVSiW4K/iE5xp6vSu9EV1PpsvReGoF+SkCvUlsBNcdGf2014Y7pzILia0efLI51yuEkLekJZvp9Ry3n3yIByoVk+lSBwh7FCTO/iz5KhQBvPHFg84s03gwWVt1bfmaB4Qp71wseC6JJhgJNL6GWsuuj49icTkNp6Nt6QkM2tYP/Dbddb0HJlVk+UNww5zH4qxeEqA9JgRdVmxudS96ptJvW7qSiZILzOH8XCJGAIcZs9L2L7JsGIbI+L5m3b81xHE2p4m7jeQkzwPYPRfIXliKfU0bVKV0Isi6H5rdhM9OpsItbD2dY61uZwyxagDKCC2JryMvvdlOJZWRJC/Xjyyv7vDiPxn9Iw0QGHF72ZsVl5FmJ2ZS+tltSK3Wdj/qVZ92DJplnMPexjN/6ZCXzLbHvaL7btHL99lu+NuU4i8rp6oVa20lwe2imyQqv1IRLGaiz23rAFB3Ovg4hpiE/3METwtELFayy7FvgyDktEV4hkJcF6DbcOqaF5kBo8MXNiHUFMMW0HdLdQORsZ4vesUuy5czT+H6GP5jN6jPjqs=
  file: "sdk-ios-onepay-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-sdk-ios-onepay
    tags: true
